FROM alpine

RUN apk add --update redis

CMD [ "redis-server" ]

# /-----------------another container example---------------------

# FROM redis:alpine

# RUN apk add --no-cache redis

# CMD [ "redis-server" ]